#!/bin/sh

## Install node dependencies
cd dashboard/
npm install
cd ../

## Setup database
sudo mysql -e "CREATE USER 'dva313'@'%' IDENTIFIED BY '';" &&\
sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dva313'@'%';" &&\
sudo mysql -e "FLUSH PRIVILEGES;" &&\
sudo mysql -u dva313 -e "CREATE DATABASE cloudnative;" &&\
sudo mysql -u dva313 cloudnative < cloudnative.sql

## Setup web-server
sudo echo "extension=mysqli" >> /etc/php/7.4/apache2/php.ini
sudo a2enmod php7.4
sudo cp -r backend/ /var/www/html/dva313
sudo systemctl start apache2.service || sudo systemctl restart apache2.service

## Setup AWS credentials
echo "Please enter your AWS key: "
read key
echo "Please enter your AWS secret key: "
read secret
echo "Please enter InstanceId of the AWS EC2 instance you want to monitor: "
read instanceid

echo "<?php 
\$credentials_Key = '$key';
\$credentials_Secret = '$secret';
\$instance_id = '$instanceid';
?>" > backend/src/credentials.php

## Generate run script
echo "#!/bin/sh 
sudo systemctl start apache2.service 
sudo systemctl start mariadb.service 
cd dashboard/ 
npm start" > run
chmod +x run

## Finished

echo "Succesfully installed"
echo "Execute './run' to start the application"
