#!/bin/sh

## Install node dependencies
cd dashboard/
npm install
cd ../

## Setup database
sudo mysql -e "CREATE USER IF NOT EXISTS 'dva313'@'%' IDENTIFIED BY '';" &&\
sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'dva313'@'%';" &&\
sudo mysql -e "FLUSH PRIVILEGES;" &&\
sudo mysql -u dva313 -e "CREATE DATABASE IF NOT EXISTS cloudnative;" &&\
sudo mysql -u dva313 cloudnative < cloudnative.sql

## Setup web-server
sudo echo "extension=mysqli" >> /etc/php/7.4/apache2/php.ini
sudo a2enmod php7.4
sudo systemctl start apache2.service || sudo systemctl restart apache2.service

## Setup AWS credentials
echo ""
echo "Please enter your AWS key: "
read key
echo "Please enter your AWS secret key: "
read secret
echo "Please enter InstanceId of the AWS EC2 instance you want to monitor: "
read instanceid
x=1
location=""
while [ $x -eq 1 ]
do
    echo "Which AWS location is you EC2 instance running on?
1. us-east-1
2. us-east-2
3. us-west-1
4. us-west-2
5. eu-north-1"
    read option
    if [ option -eq 1]; then
	location="us-east-1"
	x=2
    elif [ option -eq 2]; then
	location="us-east-2"
	x=2
    elif [ option -eq 3]; then
	location="us-west-1"
	x=2
    elif [ option -eq 4]; then
	location="us-west-2"
	x=2
    elif [ option -eq 5]; then
	location="eu-north-1"
	x=2
    else
	echo "Please enter a valid option"
    fi
done

echo "<?php
\$credentials_Key = '$key';
\$credentials_Secret = '$secret';
\$instance_id = '$instanceid';
\$location = '$location';
?>" > backend/src/credentials.php

sudo mkdir /var/www/html/dva313
sudo cp -r backend/ /var/www/html/dva313/backend

## Generate run script
echo "#!/bin/sh
sudo systemctl start apache2.service
sudo systemctl start mariadb.service
cd dashboard/
npm start" > run
chmod +x run

## Finished
echo ""
echo "Succesfully installed!"
echo "Execute './run' to start the application."
